### [예제 1]  Feed Forward 이해 및 계산 연습

In [ ]:
import numpy as np

# 활성화함수 sigmoid
def sigmoid(x):
    
    return 1 / (1 + np.exp(-x))

## Data Definition

In [ ]:
input_data = np.array([1, 2]) # 입력 데이터
target_data = np.array([1]) # 정답 데이터

In [ ]:
input_nodes = 2 # 입력층 노드 개수
hidden_nodes = 3 # 은닉층 노드 개수
output_nodes = 1 # 출력층 노드 개수

## Initialize weights and bias

In [ ]:
W2 = np.random.rand(input_nodes, hidden_nodes) # W2 정의, shape : (2, 3)
b2 = np.random.rand(hidden_nodes) # b2 정의, shape : (3, )

W3 = np.random.rand(hidden_nodes, output_nodes) # W3 정의, shape : (3, 1)
b3 = np.random.rand(output_nodes) # b3 정의, shape : (1, )

In [ ]:
print("W2 = ", W2, ", W2.shape = ", W2.shape)
print("b2 = ", b2, ", b2.shape = ", b2.shape)
print("W3 = ", W3, ", W3.shape = ", W3.shape)
print("b3 = ", b3, ", b3.shape = ", b3.shape)

W2 =  [[0.56000502 0.39383791 0.79912791]
 [0.94125064 0.28671784 0.15351819]] , W2.shape =  (2, 3)
b2 =  [0.53990407 0.38475006 0.9960264 ] , b2.shape =  (3,)
W3 =  [[0.99860046]
 [0.67466978]
 [0.07652987]] , W3.shape =  (3, 1)
b3 =  [0.50039934] , b3.shape =  (1,)


In [ ]:
def feed_forward(xdata):
    print("[feed_forward function]\n")

    Z2 = np.dot(xdata, W2) + b2

    print(f'Z2 = {Z2}')

    A2 = sigmoid(Z2)

    print(f'A2 = {A2}')

    Z3 = np.dot(A2, W3) + b3

    print(f'Z3 = {Z3}')

    Y = A3 = sigmoid(Z3)

    print(f'Y = {Y}, A3 = {A3}')

    loss = np.sum((target_data-Y)**2) / len(target_data)
    # np.sum == SIGMA , 1/N == 1/len(target_data)
    
    print('current loss val = ', loss)
    
    print("\n[feed_forward function]\n")

    return loss

#### Z2, A2, Z3, y(=A3), loss 값을 신경망 아키텍처에서 설명해볼것

In [ ]:
loss_val = feed_forward(input_data)

[feed_forward function]

Z2 = [2.98241037 1.35202366 2.10219068]
A2 = [0.95177313 0.79446027 0.89111592]
Z3 = [2.05503575]
Y = [0.88645546], A3 = [0.88645546]
current loss val =  0.012892361438075184

[feed_forward function]



# one hot encoding

In [10]:
import numpy as np
import tensorflow as tf

T = np.array([0, 1, 2, 3, 4])

Y_ONEHOT = tf.keras.utils.to_categorical(T, 5)

print(Y_ONEHOT)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
