# Module import

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

# Data Definition 

In [ ]:
input = [[2, 1, 2], [1, 2, 3], [3, 0, 2]]
label = [1, 1, 3]

In [ ]:
input_units = 3
hidden_units = 4
output_units = 5

## one hot enccoding

In [ ]:
xdata = np.array(input)
tdata = np.zeros([3,5])

for index in range(len(label)):
    tdata[index, label[index]] = 1.0  # int() 해주어서 열 인덱스에 대해 정수형 취한다

print(xdata)

for index in range(len(label)):
    
    print('label = ', label[index], ', one-hot encoding = ', tdata[index])

[[2 1 2]
 [1 2 3]
 [3 0 2]]
label =  1 , one-hot encoding =  [0. 1. 0. 0. 0.]
label =  1 , one-hot encoding =  [0. 1. 0. 0. 0.]
label =  3 , one-hot encoding =  [0. 0. 0. 1. 0.]


# Initialize weights and bias

In [ ]:
W2 = np.random.rand(input_units, hidden_units)
b2 = np.random.rand(hidden_units)

W3 = np.random.rand(hidden_units, output_units)
b3 = np.random.rand(output_units)

In [ ]:
print(f'xdata.shape = {xdata.shape}, tdata.shape = {tdata.shape}')
print(f'W2.shape = {W2.shape}, b2.shape = {b2.shape}')
print(f'W3.shape = {W3.shape}, b3.shape = {b3.shape}')

xdata.shape = (3, 3), tdata.shape = (3, 5)
W2.shape = (3, 4), b2.shape = (4,)
W3.shape = (4, 5), b3.shape = (5,)


# Define loss function and output, y

In [ ]:
A1 = xdata
A2 = sigmoid(np.dot(A1,W2)+b2)

print(A2.shape)

Y = A3 = sigmoid(np.dot(A2,W3)+b3)

print(A3.shape)

(3, 4)
(3, 5)


# Predict

In [ ]:
test_xdata = np.array([1, 1, 2])

In [ ]:
def predict(test_data):

    A1 = test_data
    A2 = sigmoid(np.dot(A1, W2)+ b2)
    sigmoid_val = sigmoid(np.dot(A2, W3)+ b3)
    Y = np.argmax(sigmoid_val)

    return Y, sigmoid_val # 사람들이 원하는 결과값과 loss를 계산하기 위한 결과 값이 다르므로 확률값과 실제값을 분리

In [ ]:
predicted_num, sigmoid_val = predict(test_xdata)

print('prediction = ',predicted_num)
print('sigmoid val = ')
print(sigmoid_val.reshape(5,1))

prediction =  0
sigmoid val = 
[[0.93967327]
 [0.9217312 ]
 [0.83655501]
 [0.92736147]
 [0.93729068]]
